In [8]:
import numpy as np
import pandas as pd

# Table-1  "Customers"

In [9]:
customers=pd.read_csv("customers.csv")
print(customers)

      customer_id           customer_name       city signup_date  \
0         C100000            Champak Devi    Chennai  2025-04-28
1         C100001            Xavier Loyal  Hyderabad  2026-01-19
2         C100002            Upkaar Sodhi  Bangalore  2026-05-27
3         C100003              Megha Mani       Pune  2026-04-12
4         C100004  Urishilla Venkataraman    Kolkata  2025-12-20
...           ...                     ...        ...         ...
21995     C121995              Aashi Pant      Delhi  2026-01-31
21996     C121996               Jeet Rama    Chennai  2026-06-26
21997     C121997        Sudiksha Trivedi      Delhi  2026-03-26
21998     C121998             Anamika Jha    Chennai  2026-07-12
21999     C121999         Gabriel Chokshi    Kolkata  2025-12-08

       activity_score
0            5.790691
1            2.228027
2            1.955856
3            0.777515
4            0.294370
...               ...
21995        3.918411
21996        3.115955
21997        0.786901
21998        1.206546
21999        1.377206

[22000 rows x 5 columns]

In [10]:
# Check Null
customers.isnull().sum()

customer_id       0
customer_name     0
city              0
signup_date       0
activity_score    0
dtype: int64

In [11]:
# Check Duplicate
customers["customer_id"].duplicated().sum()
customers["customer_name"].duplicated().sum()
customers["city"].duplicated().sum()
customers["signup_date"].duplicated().sum()
customers["activity_score"].duplicated().sum()

np.int64(0)

In [12]:
# City check
customers["city"].value_counts()

city
Delhi        5221
Bangalore    4418
Mumbai       3128
Hyderabad    2661
Pune         2377
Chennai      2225
Kolkata      1970
Name: count, dtype: int64

In [13]:
# Date Range
a=customers["signup_date"].min()
print(a)
b=customers["signup_date"].max()
print(b)

2025-02-17
2026-08-09

In [14]:
x=customers["signup_date"] = pd.to_datetime(customers["signup_date"])
print(x)

0       2025-04-28
1       2026-01-19
2       2026-05-27
3       2026-04-12
4       2025-12-20
           ...
21995   2026-01-31
21996   2026-06-26
21997   2026-03-26
21998   2026-07-12
21999   2025-12-08
Name: signup_date, Length: 22000, dtype: datetime64[ns]

In [15]:
# Activity score Range
customers["activity_score"].describe()

count    22000.000000
mean         1.993511
std          1.423715
min          0.007942
25%          0.946114
50%          1.658502
75%          2.689129
max         13.557106
Name: activity_score, dtype: float64

In [16]:
# Export cleaned file
customers.to_csv('cleaned_customers.csv', index=False)
print("Saved successfully as cleaned_customer.csv!")

Saved successfully as cleaned_customer.csv!

# Table2 "Order_items"

In [17]:
order_items=pd.read_csv("order_items.csv")
print(order_items)

        order_id product_id              category  quantity  unit_price  \
0      ORD500000      P0031  Household Essentials         1      224.24
1      ORD500001      P0020    Snacks & Beverages         2      124.48
2      ORD500002      P0039         Personal Care         1      194.23
3      ORD500002      P0007   Fruits & Vegetables         2       34.80
4      ORD500003      P0014     Dairy & Breakfast         1       42.96
...          ...        ...                   ...       ...         ...
90078  ORD564321      P0028  Household Essentials         1      215.41
90079  ORD564322      P0006   Fruits & Vegetables         2       54.49
90080  ORD564322      P0009   Fruits & Vegetables         1       50.54
90081  ORD564323      P0008   Fruits & Vegetables         1       17.24
90082  ORD564324      P0012     Dairy & Breakfast         2      149.34

       line_total
0          224.24
1          248.96
2          194.23
3           69.60
4           42.96
...           ...
90078      215.41
90079      108.98
90080       50.54
90081       17.24
90082      298.68

[90083 rows x 6 columns]

In [18]:
# Check Null
order_items.isnull().sum()

order_id      0
product_id    0
category      0
quantity      0
unit_price    0
line_total    0
dtype: int64

In [19]:
order_items.head()

,order_id,product_id,category,quantity,unit_price,line_total
0,ORD500000,P0031,Household Essentials,1,224.24,224.24
1,ORD500001,P0020,Snacks & Beverages,2,124.48,248.96
2,ORD500002,P0039,Personal Care,1,194.23,194.23
3,ORD500002,P0007,Fruits & Vegetables,2,34.80,69.60
4,ORD500003,P0014,Dairy & Breakfast,1,42.96,42.96

In [20]:
# Check total duplicates
order_items.duplicated().sum()

np.int64(373)

In [21]:
# Check Duplicate
order_items["order_id"].duplicated()
order_items["category"].duplicated()
order_items["quantity"].duplicated()
order_items["unit_price"].duplicated()
order_items["line_total"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
90078     True
90079     True
90080     True
90081     True
90082     True
Name: line_total, Length: 90083, dtype: bool

In [22]:
order_items = order_items.drop_duplicates().reset_index(drop=True)
order_items

,order_id,product_id,category,quantity,unit_price,line_total
0,ORD500000,P0031,Household Essentials,1,224.24,224.24
1,ORD500001,P0020,Snacks & Beverages,2,124.48,248.96
2,ORD500002,P0039,Personal Care,1,194.23,194.23
3,ORD500002,P0007,Fruits & Vegetables,2,34.80,69.60
4,ORD500003,P0014,Dairy & Breakfast,1,42.96,42.96
...,...,...,...,...,...,...
89705,ORD564321,P0028,Household Essentials,1,215.41,215.41
89706,ORD564322,P0006,Fruits & Vegetables,2,54.49,108.98
89707,ORD564322,P0009,Fruits & Vegetables,1,50.54,50.54
89708,ORD564323,P0008,Fruits & Vegetables,1,17.24,17.24
89709,ORD564324,P0012,Dairy & Breakfast,2,149.34,298.68

In [23]:
# Check total duplicates after filling
order_items.duplicated().sum()

np.int64(0)

In [24]:
# Check unique categories
x=order_items["category"].unique()
print(x)

['Household Essentials' 'Snacks & Beverages' 'Personal Care'
 'Fruits & Vegetables' 'Dairy & Breakfast' 'Others']

In [25]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89710 entries, 0 to 89709
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    89710 non-null  object
 1   product_id  89710 non-null  object
 2   category    89710 non-null  object
 3   quantity    89710 non-null  int64
 4   unit_price  89710 non-null  float64
 5   line_total  89710 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 4.1+ MB

In [26]:
# Downcast / optimize data types for dashboard & ML performance
order_items['quantity'] = order_items['quantity'].astype('int16')
order_items['category'] = order_items['category'].astype('category')
order_items['unit_price'] =order_items['unit_price'].round(2)
order_items['line_total'] = order_items['line_total'].round(2)

In [27]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89710 entries, 0 to 89709
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    89710 non-null  object
 1   product_id  89710 non-null  object
 2   category    89710 non-null  category
 3   quantity    89710 non-null  int16
 4   unit_price  89710 non-null  float64
 5   line_total  89710 non-null  float64
dtypes: category(1), float64(2), int16(1), object(2)
memory usage: 3.0+ MB

In [28]:
# Export cleaned file
order_items.to_csv('cleaned_order_items.csv', index=False)
print("Saved successfully as cleaned_order_items.csv!")

Saved successfully as cleaned_order_items.csv!

# Table-3  "Orders"

In [29]:
orders=pd.read_csv("orders.csv")
print(orders)

        order_id customer_id       city      order_timestamp     status  \
0      ORD500000     C114573    Chennai  2026-05-19 20:20:00  Delivered
1      ORD500001     C117353      Delhi  2026-05-19 15:22:00  Delivered
2      ORD500002     C109281      Delhi  2026-05-19 19:44:00  Delivered
3      ORD500003     C115595      Delhi  2026-05-19 16:22:00  Delivered
4      ORD500004     C102888  Bangalore  2026-05-19 07:20:00  Delivered
...          ...         ...        ...                  ...        ...
64320  ORD564320     C112066      Delhi  2026-08-17 16:22:00  Delivered
64321  ORD564321     C119969    Chennai  2026-08-17 18:58:00  Confirmed
64322  ORD564322     C120797      Delhi  2026-08-17 10:07:00  Cancelled
64323  ORD564323     C114515      Delhi  2026-08-17 23:28:00  Cancelled
64324  ORD564324     C103382    Kolkata  2026-08-17 20:24:00  Delivered

      payment_method rider_id  delivery_time_mins  gross_amount  discount  \
0                COD    R1735                16.0        224.24     29.13
1                UPI    R1230                38.0        248.96      0.00
2                UPI    R1035                22.0        263.83      0.00
3                UPI    R1137                44.0        112.07      0.00
4                UPI    R1357                29.0        228.04     30.96
...              ...      ...                 ...           ...       ...
64320            UPI    R1451                12.0        441.02      0.00
64321            COD      NaN                 NaN        215.41      0.00
64322            COD      NaN                 NaN        159.52      0.00
64323            UPI      NaN                 NaN         17.24      0.00
64324            UPI    R1780                33.0        298.68     31.46

       delivery_fee  platform_fee  net_amount
0                 0          3.00      198.11
1                 0          5.05      254.01
2                15          3.53      282.36
3                35          4.97      152.04
4                15          5.16      217.24
...             ...           ...         ...
64320            15          5.24      461.26
64321            15          3.89      234.30
64322            15          5.37      179.89
64323            25          3.69       45.93
64324             0          3.61      270.83

[64325 rows x 13 columns]

In [30]:
# Check Null
orders.isnull().sum()

order_id                  0
customer_id               0
city                      0
order_timestamp           0
status                    0
payment_method            0
rider_id               7741
delivery_time_mins    18388
gross_amount              0
discount                  0
delivery_fee              0
platform_fee              0
net_amount                0
dtype: int64

In [31]:
#  Datetime conversion & Date/Time features

orders['order_timestamp'] = pd.to_datetime(orders['order_timestamp'])
orders['order_date'] = orders['order_timestamp'].dt.date
orders['order_hour'] = orders['order_timestamp'].dt.hour
orders['day_of_week'] = orders['order_timestamp'].dt.day_name()
orders['is_weekend'] = orders['order_timestamp'].dt.dayofweek.isin([5, 6]).astype(int)

In [32]:
# Rider ID nulls ko explicit category dena

orders['rider_id'] = orders['rider_id'].fillna('Unassigned')

In [33]:
# Again Check Null
orders.isnull().sum()

order_id                  0
customer_id               0
city                      0
order_timestamp           0
status                    0
payment_method            0
rider_id                  0
delivery_time_mins    18388
gross_amount              0
discount                  0
delivery_fee              0
platform_fee              0
net_amount                0
order_date                0
order_hour                0
day_of_week               0
is_weekend                0
dtype: int64

In [34]:
orders.to_csv('cleaned_orders.csv', index=False)
print("Orders table successfully cleaned & saved as cleaned_orders.csv!")

Orders table successfully cleaned & saved as cleaned_orders.csv!

# Table -4 "Products"

In [35]:
products=pd.read_csv("products.csv")
print(products)

   product_id        product_name              category  unit_price
0       P0001              Tomato   Fruits & Vegetables       39.35
1       P0002               Onion   Fruits & Vegetables       18.78
2       P0003              Potato   Fruits & Vegetables       69.11
3       P0004              Banana   Fruits & Vegetables       43.08
4       P0005               Apple   Fruits & Vegetables       44.64
5       P0006             Spinach   Fruits & Vegetables       54.49
6       P0007            Cucumber   Fruits & Vegetables       34.80
7       P0008              Carrot   Fruits & Vegetables       17.24
8       P0009               Mango   Fruits & Vegetables       50.54
9       P0010        Green Chilli   Fruits & Vegetables       53.86
10      P0011          Milk 500ml     Dairy & Breakfast       67.06
11      P0012           Curd 400g     Dairy & Breakfast      149.34
12      P0013         Paneer 200g     Dairy & Breakfast      151.40
13      P0014               Bread     Dairy & Breakfast       42.96
14      P0015          Eggs (6pc)     Dairy & Breakfast       75.40
15      P0016         Butter 100g     Dairy & Breakfast      135.55
16      P0017        Cheese Slice     Dairy & Breakfast       91.27
17      P0018                Oats     Dairy & Breakfast      103.83
18      P0019          Lays Chips    Snacks & Beverages       57.67
19      P0020     Coca Cola 750ml    Snacks & Beverages      124.48
20      P0021       Biscuits Pack    Snacks & Beverages       61.34
21      P0022        Namkeen 200g    Snacks & Beverages       20.90
22      P0023            Juice 1L    Snacks & Beverages      142.58
23      P0024         Coffee 100g    Snacks & Beverages      145.12
24      P0025            Tea 250g    Snacks & Beverages       99.24
25      P0026       Chocolate Bar    Snacks & Beverages       38.84
26      P0027           Dish Soap  Household Essentials      192.93
27      P0028       Detergent 1kg  Household Essentials      215.41
28      P0029      Toilet Cleaner  Household Essentials       43.48
29      P0030       Floor Cleaner  Household Essentials      121.21
30      P0031        Garbage Bags  Household Essentials      224.24
31      P0032         Tissue Roll  Household Essentials       90.79
32      P0033  Mosquito Repellent  Household Essentials      113.33
33      P0034       Shampoo 200ml         Personal Care       90.41
34      P0035            Soap Bar         Personal Care       51.27
35      P0036          Toothpaste         Personal Care      228.04
36      P0037           Face Wash         Personal Care      214.40
37      P0038      Hand Sanitizer         Personal Care      293.25
38      P0039         Body Lotion         Personal Care      194.23
39      P0040               Razor         Personal Care      211.37
40      P0041            Notebook                Others      373.48
41      P0042       Phone Charger                Others      172.49
42      P0043           Batteries                Others      287.53
43      P0044             Candles                Others      221.78
44      P0045        Pet Food 1kg                Others      138.63
45      P0046      Stationery Kit                Others      215.56

In [36]:
#  Data Types & Rounding
products['unit_price'] = products['unit_price'].round(2)
products['category'] = products['category'].astype('category')

In [37]:
products.head()

  product_id product_name             category  unit_price
0      P0001       Tomato  Fruits & Vegetables       39.35
1      P0002        Onion  Fruits & Vegetables       18.78
2      P0003       Potato  Fruits & Vegetables       69.11
3      P0004       Banana  Fruits & Vegetables       43.08
4      P0005        Apple  Fruits & Vegetables       44.64

In [38]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64325 entries, 0 to 64324
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            64325 non-null  object
 1   customer_id         64325 non-null  object
 2   city                64325 non-null  object
 3   order_timestamp     64325 non-null  datetime64[ns]
 4   status              64325 non-null  object
 5   payment_method      64325 non-null  object
 6   rider_id            64325 non-null  object
 7   delivery_time_mins  45937 non-null  float64
 8   gross_amount        64325 non-null  float64
 9   discount            64325 non-null  float64
 10  delivery_fee        64325 non-null  int64
 11  platform_fee        64325 non-null  float64
 12  net_amount          64325 non-null  float64
 13  order_date          64325 non-null  object
 14  order_hour          64325 non-null  int32
 15  day_of_week         64325 non-null  object
 16  is_weekend          64325 non-null  int64
dtypes: datetime64[ns](1), float64(5), int32(1), int64(2), object(8)
memory usage: 8.1+ MB

In [39]:
products.category

0      Fruits & Vegetables
1      Fruits & Vegetables
2      Fruits & Vegetables
3      Fruits & Vegetables
4      Fruits & Vegetables
5      Fruits & Vegetables
6      Fruits & Vegetables
7      Fruits & Vegetables
8      Fruits & Vegetables
9      Fruits & Vegetables
10       Dairy & Breakfast
11       Dairy & Breakfast
12       Dairy & Breakfast
13       Dairy & Breakfast
14       Dairy & Breakfast
15       Dairy & Breakfast
16       Dairy & Breakfast
17       Dairy & Breakfast
18      Snacks & Beverages
19      Snacks & Beverages
20      Snacks & Beverages
21      Snacks & Beverages
22      Snacks & Beverages
23      Snacks & Beverages
24      Snacks & Beverages
25      Snacks & Beverages
26    Household Essentials
27    Household Essentials
28    Household Essentials
29    Household Essentials
30    Household Essentials
31    Household Essentials
32    Household Essentials
33           Personal Care
34           Personal Care
35           Personal Care
36           Personal Care
37           Personal Care
38           Personal Care
39           Personal Care
40                  Others
41                  Others
42                  Others
43                  Others
44                  Others
45                  Others
Name: category, dtype: category
Categories (6, object): ['Dairy & Breakfast', 'Fruits & Vegetables', 'Household Essentials', 'Others', 'Personal Care', 'Snacks & Beverages']

In [40]:
products.product_name

0                 Tomato
1                  Onion
2                 Potato
3                 Banana
4                  Apple
5                Spinach
6               Cucumber
7                 Carrot
8                  Mango
9           Green Chilli
10            Milk 500ml
11             Curd 400g
12           Paneer 200g
13                 Bread
14            Eggs (6pc)
15           Butter 100g
16          Cheese Slice
17                  Oats
18            Lays Chips
19       Coca Cola 750ml
20         Biscuits Pack
21          Namkeen 200g
22              Juice 1L
23           Coffee 100g
24              Tea 250g
25         Chocolate Bar
26             Dish Soap
27         Detergent 1kg
28        Toilet Cleaner
29         Floor Cleaner
30          Garbage Bags
31           Tissue Roll
32    Mosquito Repellent
33         Shampoo 200ml
34              Soap Bar
35            Toothpaste
36             Face Wash
37        Hand Sanitizer
38           Body Lotion
39                 Razor
40              Notebook
41         Phone Charger
42             Batteries
43               Candles
44          Pet Food 1kg
45        Stationery Kit
Name: product_name, dtype: object

In [41]:
#  Save Cleaned Dimension Table
products.to_csv('cleaned_products.csv', index=False)
print("Products table cleaned and saved as cleaned_products.csv!")

Products table cleaned and saved as cleaned_products.csv!

# Table-5 "riders"

In [42]:
riders=pd.read_csv("riders.csv")
print(riders)

    rider_id      rider_name       city  rating  is_active
0      R1000  Sarthak Pillai      Delhi     4.5      False
1      R1001     Tarak Koshy    Chennai     3.6       True
2      R1002      Leela Kota  Hyderabad     4.3      False
3      R1003  Mohammed Tella      Delhi     4.0       True
4      R1004     Wazir Kanda       Pune     4.7      False
..       ...             ...        ...     ...        ...
895    R1895  Garima Chokshi    Chennai     4.0       True
896    R1896       Avi Palla      Delhi     5.0       True
897    R1897   Vivaan Dhawan      Delhi     5.0       True
898    R1898     Zayan Memon     Mumbai     4.8      False
899    R1899    Atharv Boase     Mumbai     4.8       True

[900 rows x 5 columns]

In [43]:
riders.shape

(900, 5)

In [44]:
# Check Null
riders.isnull().sum()

rider_id      0
rider_name    0
city          0
rating        0
is_active     0
dtype: int64

In [45]:
# duplicate
riders.duplicated().sum()

np.int64(0)

In [46]:
# optimize type
riders['rating'] = riders['rating'].round(1)

In [47]:
#   Save
riders.to_csv('cleaned_riders.csv', index=False)
print("Riders table verified and ready!")

Riders table verified and ready!